version: '2'
services:
  db:
    restart: always
    image: postgres:9.6
    volumes:
      - /testfider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd

  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    environment: 
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable
      JWT_SECRET: tXQhvSMWMS11qZ9euEhE6lf2ferf0FR6RYGd8iMXiTxxXtJ1XDVdTXPaLtV12ZGp
      EMAIL_NOREPLY: noreply@yourdomain.com

      ###
      # EMAIL
      #
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      # EMAIL_MAILGUN_API: key-yourkeygoeshere
      # EMAIL_MAILGUN_DOMAIN: yourdomain.com

      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: benamorelyes0@gmail.com
      EMAIL_SMTP_PASSWORD: Azertyuiop123456789.
      #EMAIL_SMTP_SSL: enable
      # GitHub
      OAUTH_GITHUB_CLIENTID: 8bf25d5a40548ac247a8
      OAUTH_GITHUB_SECRET: 853a873ea6902c26369e1187c142fbacb03a46d5
      

      #GITLAB
      
      

    depends_on:
      - db