apiVersion: apps/v1
kind: Deployment
metadata:
  name: fider
  labels:
    app: fider
spec:
  selector:
    matchLabels:
      app: fider
      tier: fider
  replicas: 2
  template:
    metadata:
      labels:
        app: fider
        tier: fider
    spec:
      containers:
      - name: fider
        image: getfider/fider:stable
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        
        ports:
        - containerPort: 3000