apiVersion: apps/v1 # 
kind: Deployment
metadata:
  name: fider
  labels:
    app: fider
spec:
  selector:
    matchLabels:
      app: fider
      tier: fider
  replicas: 2
  template:
    metadata:
      labels:
        app: fider
        tier: fider
    spec:
      containers:
      - name: fider
        image: getfider/fider:stable
        resources:
          requests:
            cpu: 100m
            memory: 10Gi
        env: 
          - name: EMAIL_NOREPLY
            value: noreply@yourdomain.com
          - name: EMAIL_SMTP_HOST
            value: smtp.gmail.com
          - name: EMAIL_SMTP_PORT
            value: 587
          - name: EMAIL_SMTP_USERNAME
            value: benamorelyes0@gmail.com
          - name: EMAIL_SMTP_PASSWORD
            value: Azertyuiop123456789.
          #EMAIL_SMTP_SSL: enable
          # GitHub
          - name: OAUTH_GITHUB_CLIENTID
            value: 8bf25d5a40548ac247a8
          - name: OAUTH_GITHUB_SECRET
            value: 853a873ea6902c26369e1187c142fbacb03a46d5
        ports:
        - containerPort: 3000