kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-claim0
  labels:
    #type: local
    io.kompose.service: db-claim0
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"